huh:
    list:
        managers:
            - { name: default, id: huh.list.manager.list }
        lists:
            - { name: default, class: HeimrichHannot\ListBundle\Lists\DefaultList }
        items:
            - { name: default, class: HeimrichHannot\ListBundle\Item\DefaultItem }
        config_element_types:
            - { name: image, class: HeimrichHannot\ListBundle\ConfigElementType\ImageConfigElementType }
        templates:
            list:
                - { name: default, template: "@HeimrichHannotContaoList/list/list_default.html.twig" }
                - { name: table_default, template: "@HeimrichHannotContaoList/list/list_table_default.html.twig" }
            item:
                - { name: default, template: "@HeimrichHannotContaoList/item/list_item_default.html.twig" }
                - { name: table_default, template: "@HeimrichHannotContaoList/item/list_item_table_default.html.twig" }