huh:
    list:
        managers:
            - { name: default, id: huh.list.manager.list }
        lists:
            - { name: default, class: HeimrichHannot\ListBundle\Lists\DefaultList }
        items:
            - { name: default, class: HeimrichHannot\ListBundle\Item\DefaultItem }
        templates:
            list:
                - { name: default, template: "@HeimrichHannotContaoList/list/list_default.html.twig" }
                - { name: table_default, template: "@HeimrichHannotContaoList/list/list_table_default.html.twig" }
            list_prefixes:
                - list_(?!item)
            item:
                - { name: default, template: "@HeimrichHannotContaoList/item/list_item_default.html.twig" }
                - { name: table_default, template: "@HeimrichHannotContaoList/item/list_item_table_default.html.twig" }
            item_prefixes:
                - list_item_
                - item_
                - news_
                - event_
            item_choice:
              - { name: default, template: "@HeimrichHannotContaoList/item_choice/list_item_choice_default.html.twig" }
            item_choice_prefixes:
              - list_item_choice_