services:
  huh.list.listener.search:
        class: HeimrichHannot\ListBundle\EventListener\SearchListener
        arguments:
              - "@contao.framework"
              - "@huh.list.list-config-registry"
              - "@huh.list.manager.list"