services:
    huh.list.choice.template.list:
        class: HeimrichHannot\ListBundle\Choice\ListTemplateChoice
        arguments:
            - "@contao.framework"
    huh.list.choice.template.item:
        class: HeimrichHannot\ListBundle\Choice\ListItemTemplateChoice
        arguments:
            - "@contao.framework"
    huh.list.list-config-registry:
        class: HeimrichHannot\ListBundle\Registry\ListConfigRegistry
        arguments:
            - "@contao.framework"
    huh.list.list-config-element-registry:
        class: HeimrichHannot\ListBundle\Registry\ListConfigElementRegistry
        arguments:
            - "@contao.framework"