services:
  _defaults:
    public: true
    bind:
      $bundleConfig: "%huh_list%"

  HeimrichHannot\ListBundle\:
    resource: '../../{DataContainer,EventSubscriber,ListExtension}/*'
    autoconfigure: true
    autowire: true

  huh.list.choice.parent-list-config:
    class: HeimrichHannot\ListBundle\Choice\ParentListConfigChoice
    public: true
    arguments:
    - "@contao.framework"

  HeimrichHannot\ListBundle\Manager\ListManager:
    public: true
    autowire: true

  huh.list.manager.list: '@HeimrichHannot\ListBundle\Manager\ListManager'

  huh.list.list-config-registry:
    class: HeimrichHannot\ListBundle\Registry\ListConfigRegistry
    public: true
    arguments:
    - "@contao.framework"

  HeimrichHannot\ListBundle\Registry\ListConfigElementRegistry:
    autowire: true
  huh.list.list-config-element-registry: '@HeimrichHannot\ListBundle\Registry\ListConfigElementRegistry'

  huh.list.choice.manager:
    class: HeimrichHannot\ListBundle\Choice\ManagerChoice
    arguments:
    - "@contao.framework"

  huh.list.choice.list:
    class: HeimrichHannot\ListBundle\Choice\ListChoice
    arguments:
    - "@contao.framework"

  huh.list.choice.item:
    class: HeimrichHannot\ListBundle\Choice\ItemChoice
    arguments:
    - "@contao.framework"

  huh.list.util.manager:
    class: HeimrichHannot\ListBundle\Util\ListManagerUtil
    public: true
    arguments:
    - "@contao.framework"

  # Symfony 4 autowire convention fix (ambiguous namespace alias)
  HeimrichHannot\ListBundle\Registry\ListConfigRegistry: '@huh.list.list-config-registry'
  HeimrichHannot\ListBundle\Util\ListManagerUtil: '@huh.list.util.manager'

  # List config element types
  HeimrichHannot\ListBundle\ConfigElementType\ImageConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\SubmissionFormConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\RelatedConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\TagsConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\VideoConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\Asset\FrontendAsset:
    autowire: true
    public: true
    calls:
      - [ setEncoreFrontendAsset, [ '@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset' ] ]
