services:
    huh.list.choice.template.item:
        class: HeimrichHannot\ListBundle\Choice\ListItemTemplateChoice
        arguments:
            - "@contao.framework"
    huh.list.registry:
        class: HeimrichHannot\ListBundle\Registry\ListRegistry
        arguments:
            - "@contao.framework"