services:
  _defaults:
    public: true
    bind:
      $bundleConfig: "%huh_list%"

  HeimrichHannot\ListBundle\:
    resource: '../../{Asset,Controller,DataContainer,EventSubscriber,ListExtension,Util}/*'
    autoconfigure: true
    autowire: true
    exclude: '../../Util/DC_Table_Utils.php'

  HeimrichHannot\ListBundle\Manager\ListManager:
    public: true
    autowire: true

  huh.list.manager.list: '@HeimrichHannot\ListBundle\Manager\ListManager'

  huh.list.list-config-registry:
    class: HeimrichHannot\ListBundle\Registry\ListConfigRegistry
    public: true
    arguments:
    - "@contao.framework"

  HeimrichHannot\ListBundle\Registry\ListConfigElementRegistry:
    autowire: true
  huh.list.list-config-element-registry: '@HeimrichHannot\ListBundle\Registry\ListConfigElementRegistry'

  huh.list.util.manager:
    class: HeimrichHannot\ListBundle\Util\ListManagerUtil
    public: true
    arguments:
    - "@contao.framework"

  # Symfony 4 autowire convention fix (ambiguous namespace alias)
  HeimrichHannot\ListBundle\Registry\ListConfigRegistry: '@huh.list.list-config-registry'
  HeimrichHannot\ListBundle\Util\ListManagerUtil: '@huh.list.util.manager'

  # List config element types
  HeimrichHannot\ListBundle\ConfigElementType\ImageConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\SubmissionFormConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\RelatedConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\TagsConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\VideoConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\Asset\FrontendAsset:
    autowire: true
    public: true
    autoconfigure: true
