services:
  _defaults:
    public: true
    bind:
      $bundleConfig: "%huh_list%"

  HeimrichHannot\ListBundle\DataContainer\:
    resource: '../../DataContainer/*'
    public: true
    autowire: true

  HeimrichHannot\ListBundle\EventSubscriber\:
    resource: '../../EventSubscriber/*'
    autowire: true
    autoconfigure: true
    public: false

  huh.list.choice.parent-list-config:
    class: HeimrichHannot\ListBundle\Choice\ParentListConfigChoice
    public: true
    arguments:
    - "@contao.framework"

  huh.list.manager.list:
    class: HeimrichHannot\ListBundle\Manager\ListManager
    public: true
    autowire: true

  huh.list.list-config-registry:
    class: HeimrichHannot\ListBundle\Registry\ListConfigRegistry
    public: true
    arguments:
    - "@contao.framework"

  HeimrichHannot\ListBundle\Registry\ListConfigElementRegistry:
    autowire: true
  huh.list.list-config-element-registry: '@HeimrichHannot\ListBundle\Registry\ListConfigElementRegistry'

  huh.list.choice.manager:
    class: HeimrichHannot\ListBundle\Choice\ManagerChoice
    arguments:
    - "@contao.framework"

  huh.list.choice.list:
    class: HeimrichHannot\ListBundle\Choice\ListChoice
    arguments:
    - "@contao.framework"

  huh.list.choice.item:
    class: HeimrichHannot\ListBundle\Choice\ItemChoice
    arguments:
    - "@contao.framework"

  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
    - { name: twig.extension }

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
    - { name: twig.extension }

  twig.extension.array:
    class: Twig_Extensions_Extension_Array
    tags:
    - { name: twig.extension }

  twig.extension.date:
    class: Twig_Extensions_Extension_Date
    tags:
    - { name: twig.extension }
    arguments:
    - "@translator"

  huh.list.util.manager:
    class: HeimrichHannot\ListBundle\Util\ListManagerUtil
    public: true
    arguments:
    - "@contao.framework"

  twig.truncate.service:
    class: Urodoz\Truncate\TruncateService

  twig.extension.truncate.html:
    class: Urodoz\Truncate\Bridge\Twig\TruncateExtension
    arguments:
    - "@twig.truncate.service"
    tags:
    - { name: twig.extension }
  # Symfony 4 autowire convention fix (ambiguous namespace alias)
  HeimrichHannot\ListBundle\Registry\ListConfigRegistry: '@huh.list.list-config-registry'
  HeimrichHannot\ListBundle\Util\ListManagerUtil: '@huh.list.util.manager'

  # List config element types
  HeimrichHannot\ListBundle\ConfigElementType\ImageConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\SubmissionFormConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\RelatedConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\TagsConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\ConfigElementType\VideoConfigElementType:
    autowire: true
    tags: ['huh.list.config_element_type']

  HeimrichHannot\ListBundle\Asset\FrontendAsset:
    autowire: true
    public: true
    calls:
      - [ setEncoreFrontendAsset, [ '@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset' ] ]
